name: 02 - Docker Build Local

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  # Job 1: Docker Build
  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Bereitet Buildx vor, das für moderne Multi-Stage Builds nötig ist
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Baut das Image und lädt es in den lokalen Daemon (load: true)
      - name: Build and Export
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: false
          load: true
          tags: demo-app:local

      # Verifikation: Zeigt an, ob das Image nun verfügbar ist
      - name: Verify Image Presence
        run: |
          docker images demo-app:local
